### ISSUE TITLE
custom templates

### ISSUE THREAD

**Issue by lorvent** [laralib/l5scaffold#1]
Hey... really nice idea

I was missing scaffold from way/generators badly and you made it.

as in original generators (way/generators).. do you have custom templates option?

Thanks.

**Comment by fernandobritofl** [comment]
Hi @lorvent,
not yet.. but for now, you can change the files .stub in /vendor/laralib/l5scaffold/src/stubs/
Thanks.

**Comment by lorvent** [comment]
how easy to convert this into core code

i.e. instead of using it as a composer package, i want to hard code into my application.

is that tough?

thanks.

**Comment by TheBox193** [comment]
@lorvent I think your question might be unclear.

**Comment by lorvent** [comment]
Sorry, i meant to say....

Instead of using package, i want to hard code its complete code into my project.

I am asking how easy it is to achieve above thing.

**Comment by TheBox193** [comment]
Composer is a nice way to go, it's very simple. I recommend it. Does composer not work for you? or have you tried it?

**Comment by ignasbernotas** [comment]
@lorvent Fork the project, change the stub files and install your fork via composer :)
