### ISSUE TITLE
Scaffold without migration

### ISSUE THREAD

**Issue by jerrycoe** [laralib/l5scaffold#16]
Is it possible to update the package and be able to create a scaffold without a migration? Sometimes I pull in packages that already publish their own migrations and making another boilerplate one isn't necessary. or at least --schema="". But that option needs a value

**Comment by raphaelheitor** [comment]
@jerrycoe,
Now is possible call scaffold without option --schema. Try this and come back with your feedback.

Thx.

**Comment by arieltoledo** [comment]
Hi, I already have my migrations runs, but whe I run `php artisan make:scaffold` i get the ** [Symfony\Component\Console\Exception\RuntimeException]  
  Not enough arguments (missing: "name").**

**Comment by arieltoledo** [comment]
And if I try to run a scaffold the way the readme say I got [Symfony\Component\Console\Exception\InvalidArgumentException]  
  The "prefix" option does not exist.

**Comment by raphaelheitor** [comment]
@arieltoledo 
you need define the name of Entity, same in the example from readme: Tweet.

**Comment by raphaelheitor** [comment]
@arieltoledo 
do you use the version 1.0.7? This feature its only avaliable in 1.0.7.
