### ISSUE TITLE
Cant install this package

### ISSUE THREAD

**Issue by jcribeirooo** [laralib/l5scaffold#19]
Hello, as the title says I cant install this package through composer.

I get an error saying:

Could not find package 'laralib/l5scaffold' at anyversion for your minimun -stability (stable). Check the package spelling or your minimum-stability

**Comment by hopewise** [comment]
Me too, I could not install it, if I run this command:

    composer require 'laralib/l5scaffold' --dev

I get this error:

Deprecation Notice: Composer\Package\Version\VersionParser::parseLinks is deprecated. Use \Composer\Package\Loader\ArrayLoader::parseLinks() instead in phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Package/Version/VersionParser.php:226

**Comment by luego** [comment]
Try 
**composer require laralib/l5scaffold --dev**

instead of 

**composer require 'laralib/l5scaffold' --dev**

it worked for me.
