### ISSUE TITLE
Route naming (pluralization) issue in views. 

### ISSUE THREAD

**Issue by jjbandit** [laralib/l5scaffold#24]
Thanks for the great package!  I'm coming from Rails and feel right at home :)

Ran into an issue with the views generation pluralizing the route name, resulting in:

Route [inventories.store] not defined. 

Steps to reproduce:
1. Install from master to workaround #9 - in composer.json

```json
  "repositories": [
        {
            "type": "git",
            "url": "https://github.com/laralib/l5scaffold"
        }
    ],
    "require-dev": {
       "laralib/l5scaffold": "dev-master"
    },
```
and run:

$ composer update

2. Generate Inventories scaffold.  The exact command I ran is:

$ php artisan make:scaffold Inventory --schema="inventory_product:integer, sale_price:integer, quantity:integer" 

I don't have time to fix the issue today but if anyone can give me a push in the right direction I may have time in the future.

UPDATE:

The erronious route name also appears in the controller.

**Comment by fernandobritofl** [comment]
Hi @jjbandit, I think that was fixed.. take a look please.
tks
