### ISSUE TITLE
unable to create scaffold

### ISSUE THREAD

**Issue by HarryBosh** [laralib/l5scaffold#25]
While the migration and seeder are created, it soon halts with this...

 [InvalidArgumentException]
  The "--no-migration" option does not exist.

**Comment by sylviot** [comment]
What version of your Laravel?

**Comment by HarryBosh** [comment]
5.1

On Tue, Oct 6, 2015 at 1:13 PM, Sylvio Tavares <notifications@github.com>
wrote:

> What version of your Laravel?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/laralib/l5scaffold/issues/25#issuecomment-145723064>.
>



-- 
-- 
Interludic
0478 067 271

http://interludic.com.au

PO BOX 519
Prahran 3181
Victoria

**Comment by sylviot** [comment]
In file src/Makes/MakeModel.php have a protected function start(), try add 

'--no-migration' => true


in array after  'name' => $name,

:+1:

**Comment by kuttumiah** [comment]
For **Laravel 5.1.x** this issue is fixed by merging Pull request https://github.com/laralib/l5scaffold/pull/14
