### ISSUE TITLE
I hope the view of edit add {{ old('body') }}

### ISSUE THREAD

**Issue by RikiWong** [laralib/l5scaffold#26]
when I edit form no pass the validate, the body or title attr is data from the database,I hope can add {{ old('attr') }} in tpl.

**Comment by fernandobritofl** [comment]
It's nice idea!

**Comment by RikiWong** [comment]
let's go!!!!

**Comment by RikiWong** [comment]
thanks

**Comment by raphaelheitor** [comment]
@RikiWong 
please check version 1.0.9 to check this feature. 
Feedback please.

**Comment by RikiWong** [comment]
Tomorrow I will to try, Thanks

**Comment by raphaelheitor** [comment]
@RikiWong 
by feedback the other issue, I think it's ok.
