### ISSUE TITLE
when I go to the 'show' page the position of 'edit' button is not good

### ISSUE THREAD

**Issue by RikiWong** [laralib/l5scaffold#27]
![2015-10-17 12 33 48](https://cloud.githubusercontent.com/assets/8214265/10557015/5d1f1f9c-74cb-11e5-8d8b-ba6e95dc15e5.png)

**Comment by raphaelheitor** [comment]
Hi,

l5scaffold layout it's only a template help. For either customization on layout, feel free to change for your own site.
