### ISSUE TITLE
when I use scaffold view,I hope the text of manage buttons(view edit delete) have translate.

### ISSUE THREAD

**Issue by RikiWong** [laralib/l5scaffold#28]
example:{{ trans('manage.delete') }} 
because I am from china,so I hope the view tpl can add translate.

**Comment by platedodev** [comment]
Solved here [](https://github.com/laralib/l5scaffold/pull/47)

**Comment by raphaelheitor** [comment]
@platedodev , before accepting PR, resolve conflicts.

**Comment by platedodev** [comment]
@raphaelheitor done mate.

**Comment by RikiWong** [comment]
thanks, I will close the issue
