### ISSUE TITLE
readme instructions do not work

### ISSUE THREAD

**Issue by petermichaux** [laralib/l5scaffold#31]
I followed the instructions in the readme for a brand new Laravel app. I did the following which did not end well. See the error message at the bottom.

```
$ laravel new myapp
...

$ cd myapp/

$ composer require 'laralib/l5scaffold' --dev
Using version ^1.0 for laralib/l5scaffold
./composer.json has been updated
> php artisan clear-compiled
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing laralib/l5scaffold (1.0.4)
    Loading from cache

Writing lock file
Generating autoload files
> php artisan optimize
Generating optimized class loader

$ vim config/app.php 

$ php artisan

  [ReflectionException]                                
  Class Illuminate\Foundation\Composer does not exist 
```

**Comment by mortenscheel** [comment]
Edit this file
`vendor/laralib/l5scaffold/src/Commands/ScaffoldMakeCommand.php`
Change this line
`use Illuminate\Foundation\Composer;`
to
`use Illuminate\Support\Composer;`

**Comment by fernandobritofl** [comment]
ScaffoldMakeCommand.php was fixed

**Comment by morsaPT** [comment]
I've ran the composer require 'laralib/l5scaffold' --dev using Laravel 5.2.23 and I got the same error. Using the @mortenscheel solution got me up and running but I guess it's better check the ScaffoldMakeCommand.php. Thanks for the package! +1 :)

**Comment by gilcierweb** [comment]
Use
`composer require 'laralib/l5scaffold:dev-master' --dev --prefer-source`
