### ISSUE TITLE
#32

### ISSUE THREAD

**Issue by tajulasri** [laralib/l5scaffold#32]
[ReflectionException]                                
  Class Illuminate\Foundation\Composer does not exist for Laravel 5.2

"The Illuminate\Foundation\Support\Composer class has been moved to Illuminate\Support\Composer."

**Solution

change import class in ```Laralib\L5scaffold\Commands\ScaffoldMakeCommand ``` by replace  

``` Illuminate\Foundation\Composer; ```
to
``` use Illuminate\Support\Composer; ```

**Comment by fernandobritofl** [comment]
Fixed! tks @tajulasri
