### ISSUE TITLE
Composer service provider issue

### ISSUE THREAD

**Issue by MohamedQabbani** [laralib/l5scaffold#33]
Can not add "Laralib\L5scaffold\GeneratorsServiceProvider" to app config provider

 "require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.2.*"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~4.0",
        "symfony/css-selector": "2.8.*|3.0.*",
        "symfony/dom-crawler": "2.8.*|3.0.*",
        "laralib/l5scaffold": "^1.0"
    },

**Comment by morsaPT** [comment]
@MohamedQabbani what is the problem? 
Are you putting that line on your project folder in /config/app.php like this :

`   \ 'providers' => [
        
        // Laravel Framework Service Providers...
        Illuminate\Auth\AuthServiceProvider::class,
        Illuminate\Broadcasting\BroadcastServiceProvider::class,
        Illuminate\Bus\BusServiceProvider::class,
        Illuminate\Cache\CacheServiceProvider::class,
        Illuminate\Foundation\Providers\ConsoleSupportServiceProvider::class,
        Illuminate\Cookie\CookieServiceProvider::class,
        
        /* (...)
         a Lot of other stuff going in here
         (... )
         */
        
        /* Scaffold -  */
        \Laralib\L5scaffold\GeneratorsServiceProvider::class
    ],`

**Comment by fernandobritofl** [comment]
Any error yet?

**Comment by paynegreen** [comment]
I have the same issue trying to install the package into my project.  The error is [Symfony\Component\Debug\Exception\FatalErrorException]           
  Class 'Laracasts\Generators\GeneratorsServiceProvider' not found

**Comment by fernandobritofl** [comment]
What's Laravel version?

**Comment by paynegreen** [comment]
Laravel 5.2. It always gives me an error when I add "Laralib\L5scaffold\GeneratorsServiceProvider" to my config/app.php.

**Comment by paynegreen** [comment]
Fixed the issue by changing use Illuminate\Foundation\Composer; in vendor/laralib/l5scaffold/src/Commands/lScaffoldMakeCommand.php to use Illuminate\Support\Composer;

**Comment by kennedymarcos** [comment]
Changing ScaffoldMakeCommand.php in laralib vendor folder works nice! thx @paynegreen

**Comment by paynegreen** [comment]
@kennedymarcos happy to help.

**Comment by HectorOrdonez** [comment]
@fernandobritofl I asked around about how to do this, as I don't know. We need to fix this bug and then you as the owner tell packagist that the new version of this repository will require laravel 5.2. 

Or we can try to figure out how to solve this by not doing "dumpAutoloads" when making the Scaffold.

Now that I think about it I wonder why do you actually do that. Composer autoload and laravel views have nothing to do with each other. 

In fact it might be better to leave up to the user to run "composer dump-autoload" after scaffolding. Just like when you make "php artisan make:controller", or others.

**Comment by raphaelheitor** [comment]
Hello, 
new release launched (1.0.5).
This release fix the bug and include support to data types (date and boolean). 
Try it now.

Cheers.
