### ISSUE TITLE
Could not find package `laralib/l5scaffold` at any version for your minimum-stability (stable).

### ISSUE THREAD

**Issue by Nur777** [laralib/l5scaffold#36]
Hi! My Laravel Version is 5.2.29.
When i enter command in cmd:
`composer require `laralib/l5scaffold` --dev`
The cmd show me error:
`  [InvalidArgumentException]
Could not find package `laralib/l5scaffold` at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability`
![2016-04-19_12-50-05](https://cloud.githubusercontent.com/assets/7289118/14631543/5a2a3dbe-062d-11e6-82e5-eb4f7e6b513f.png)
How i can install this package?
P.S. Other packages have been established successfully
Im sorry for my bad English:)

**Comment by andrey-helldar** [comment]
Maybe use it?
`composer require laralib/l5scaffold:dev-master`

**Comment by VitaliiSestrenskyi** [comment]
thanks

**Comment by halaFtouhghammat** [comment]
thanks!

**Comment by ectaskforce** [comment]
Thanks.
