### ISSUE TITLE
Problem with ScaffoldMakeCommand

### ISSUE THREAD

**Issue by leoGajardo** [laralib/l5scaffold#40]
Hi,
When i installed the l5scaffold via composer with the specified command
`composer require 'laralib/l5scaffold' --dev`

My project starts to answer that
```
 [ReflectionException]
 Class Illuminate\Foundation\Composer does not exist
```

The package came with this line in the ScaffoldMakeCommand.php
`use Illuminate\Foundation\Composer;`

I just updated this line to fix this
`use Illuminate\Support\Composer;`

I think that the repository of composer has a messed up version of the package, just to alert you if you didn't know.

[]'s

**Comment by HectorOrdonez** [comment]
This is the same problem as in here:
https://github.com/laralib/l5scaffold/issues/33

Probably you are using Laravel 5.2. You'll find a solution there.

**Comment by raphaelheitor** [comment]
Hello @leoGajardo , new release launched (1.0.5).
This release fix the bug and include support to data types (date and boolean). 
Try it now.

Cheers.
