### ISSUE TITLE
Instalation error

### ISSUE THREAD

**Issue by essteffan** [laralib/l5scaffold#43]
Hy All. 

Is my first time using this package and it seems that there is an error after installation.

As Laravel's upgrade says:

"The Illuminate\Foundation\Support\Composer class has been moved to Illuminate\Support\Composer."

There's already a pull request for this: #82

Please update the master branch
Thanks

**Comment by raphaelheitor** [comment]
Hello @essteffan, new release launched (1.0.5).
This release fix the bug and include support to data types (date and boolean). 
Try it now.

Cheers.
