### ISSUE TITLE
Laravel 5.1 -  Class Illuminate\Support\Composer does not exist

### ISSUE THREAD

**Issue by cthos** [laralib/l5scaffold#44]
I think in 5.1 the class was still named `Illuminate\Foundation\Composer`, and it changed to `Illuminate\Support\Composer` in 5.2.

However: https://github.com/laralib/l5scaffold/blob/laravel-5.1/src/Commands/ScaffoldMakeCommand.php (the laravel-5.1 branch) made the change introduced in #29, and I don't think it should have?

**Comment by raphaelheitor** [comment]
@cthos ,
issue corrected. Feel free to colaborate. Thx for the warning.
