### ISSUE TITLE
Error: [Symfony\Component\Console\Exception\InvalidArgumentException]  The "prefix" option does not exist.                                                                    

### ISSUE THREAD

**Issue by projectbubble** [laralib/l5scaffold#48]
Hi,

I get this error when running `php artisan make:scaffold Tweet`

`
  [Symfony\Component\Console\Exception\InvalidArgumentException]  
  The "prefix" option does not exist.                                                                        
`

I am running L5.2.
Version 1.0.7.

**Comment by Sonampasi** [comment]
same problem!!

**Comment by raphaelheitor** [comment]
@projectbubble , @Sonampasi ,
problem solved in version 1.0.8.
Thx for advise.
