### ISSUE TITLE
View form fields missing after running make:scaffold

### ISSUE THREAD

**Issue by projectbubble** [laralib/l5scaffold#49]
After running this command:

`php artisan make:scaffold Tweet --schema="title:string:default('Tweet #1'), body:text"`

`php artisan migrate`

I do not see any form fields in the blade file.

![image](https://cloud.githubusercontent.com/assets/1962083/16422375/25c1085c-3d26-11e6-970d-d51100ac5e01.png)

Using version 1.0.8

**Comment by raphaelheitor** [comment]
@projectbubble 
yes, my fail. Corrected in version 1.0.9

**Comment by hiuryoliveira** [comment]
+1

**Comment by raphaelheitor** [comment]
@hiuryoliveira 

using the version 1.0.9?

**Comment by raphaelheitor** [comment]
@projectbubble @hiuryoliveira feedback please

**Comment by robbielove** [comment]
this does not work on the latest release, in the edit view it returns 1, it works showing the correct db value if ' old() or ' is removed

**Comment by raphaelheitor** [comment]
@robbielove ,
corrected this issue. Any problem let us know.

**Comment by raphaelheitor** [comment]
try new release.

**Comment by robbielove** [comment]
Working great, Thank You.
