### ISSUE TITLE
Error generating scaffold

### ISSUE THREAD

**Issue by chudacontreras** [laralib/l5scaffold#59]
Hello when I install the library for scaffold gives me the following error in laravel 5.1 ReflectionException]
   Class Illuminate \ Support \ Composer does not exist

this-law run the command php artisan make: scaffold Tweet but I believe migration and seeder, unemployment does not go beyond that, does not create the models, or the views or controllers as say only laravel 5.1, I have not tried in laravel 5.2 or 5.3

**Comment by sylviot** [comment]
Hello,

has a branch called **"laravel-5.1"** that solved it's problem or you can replace manually in file **"src/Commands/ScaffoldMakeCommand.php"** the line:

**use Illuminate\Support\Composer;**
to
**use Illuminate\Foundation\Composer;**

So sorry for it problems, in future new version don't has more it.

:)

**Comment by chudacontreras** [comment]
Thanks for the quick response and fix the error
