### ISSUE TITLE
create.blade template

### ISSUE THREAD

**Issue by xa-alan** [laralib/l5scaffold#6]
Quick build modules, as well as routing hints, your components are very easy to use.
Use the command on your  readme.md document,generate create.blade.php template have a little issue.
 line 30:
<button class="btn btn-primary" type="submit">Create</a>
revise ==>
<button class="btn btn-primary" type="submit">Create</button>

Thinkyou!

**Comment by raphaelheitor** [comment]
Hello @xa-alan ,
 this issue persist?

**Comment by srdavidsilva** [comment]
Olá Raphael, parabéns pelo projeto!
Estou tentando alterar as stubs para o scaffold rodar ja no meu layout, mas mesmo alterando no vendor, as views continuam sendo geradas com o padrão. Você pode me dar uma luz?

**Comment by srdavidsilva** [comment]
Desconsidere, foi um grande vacilo meu em esquecer do layout.blade que já havia sido gerado.
Obrigado!

**Comment by raphaelheitor** [comment]
@srdavidsilva Obrigado, na verdade tenho tentado ajudar mais, 
os criadores são @fernandobritofl  e @sylviot
