### ISSUE TITLE
update old scaffolds

### ISSUE THREAD

**Issue by robbielove** [laralib/l5scaffold#60]
This tool is great for making scaffolds but they need to be essentially re-created or manually updated to take advantage of updated features, instead of excluding from the list of files to be created, could you make it so that the generated code is updated using the stubs and I suppose the differences like 'diff' but forcing new changes to overwrite if different.

**Comment by sylviot** [comment]
Hello,

force erase file or diff is a little dangerous, but we can question in scaffolding time about overwrite the file.

Thx :+1:  :smile:

**Comment by robbielove** [comment]
Asking about overwrite is already seems to be a feature, what I'm trying to say is that if I make a change to a stub then we need to basically re-create those changes in the already generated scaffolds..

Surely any changes would be the difference between what was previously in the stub to what is now in the stub, in which case overwrite or merging newer differences would result in the same changes being made.

This way there is no unnecessary overwrite prompt and you could even backup the old files (those being 'overwritten') by appending a timestamp. If the users were using git for source control they could easily revert back anyway - I have used this method to see what will happen when generating test scaffolds.
