### ISSUE TITLE
Command "make:scaffold" is not defined.

### ISSUE THREAD

**Issue by yurik94** [laralib/l5scaffold#77]
> php artisan make:scaffold

```
  [Symfony\Component\Console\Exception\CommandNotFoundException]
  Command "make:scaffold" is not defined.
```

installed with:

>composer require laralib/l5scaffold:master

added (config/app.php) :
> Laralib\L5scaffold\GeneratorsServiceProvider::class,

Running on W10, EasyPHP Dev Server (Apache 2.4, **PHP 7.1**) and Laravel 5.4

**Comment by danielverissimo** [comment]
@yurik94 Try run: `composer dump-autoload`

**Comment by yurik94** [comment]
Still getting "not defined" (Laravel 5.4)

**Comment by danielverissimo** [comment]
Can be cache too...

Try run: php artisan config:clear

If not works, put your config file here.

**Comment by yurik94** [comment]
```
"C:\Program Files (x86)\EasyPHP-Devserver-17\eds-binaries\php\php713vc14x86x170621115524\php.exe" C:\Users\Hp\PhpstormProjects\DAF_Backend\artisan config:cache
Configuration cache cleared!

                                                                                 
  [Symfony\Component\Debug\Exception\FatalThrowableError]                        
  Call to undefined method Laralib\L5scaffold\GeneratorsServiceProvider::info()  
```

**Comment by yurik94** [comment]
Seems that is not autoloading...?

**Comment by yurik94** [comment]
Damn cache! It's working now! 👍 👍 

Thanks (Awesome package 🥇) !

**Comment by danielverissimo** [comment]
Nice
