### ISSUE TITLE
Getting error when trying to run scaffolding on Laravel 5.1

### ISSUE THREAD

**Issue by kuttumiah** [laralib/l5scaffold#9]
```ShellSession
$ php artisan make:scaffold Tweet --schema="name:string"
Configuring Tweet...
Migration created successfully
Seed created successfully.



  [InvalidArgumentException]
  The "--no-migration" option does not exist.
```

Though I haven't pass any ```--no-migration``` command.

Is there any help?
Thanks in advance.

**Comment by usonian** [comment]
I'm getting the same exact error with Laravel 5.1.3.

**Comment by Taytus** [comment]
Hey guys I just sent a pull request, the issue is on the file vendor/laralib/l5scaffold/src/Makes/MakeModel.php line 36. I just deleted that line ('--no-migration' => true) and all works :)

**Comment by fernandobritofl** [comment]
Okay, try again now ;). tks guys!

**Comment by kuttumiah** [comment]
Fixed by merging Pull request https://github.com/laralib/l5scaffold/pull/14
